spring:
  config:
    import: application-prod-secret.yml
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: false # 실행되는 query를 보여줌
    defer-datasource-initialization: true # spring boot 2.5 for using data.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging.level:
  org.hibernate.SQL: info
min:
  pin:
    value: 100000
max:
  pin:
    value: 999999